# DRIVER PARA MYSQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# URL de la base de datos (sin ? al final)
spring.datasource.url=jdbc:mysql://localhost:3306/UberBaseData

# CREDENCIALES DE MYSQL
spring.datasource.username=root
spring.datasource.password=halo12345

# MOSTRAR QUERIES SQL
spring.jpa.show-sql=true

# QUE HIBERNATE CREE O ACTUALICE LAS TABLAS
spring.jpa.hibernate.ddl-auto=update
